export const ENV = {
  appId: process.env.VITE_APP_ID ?? "",
  cookieSecret: process.env.JWT_SECRET ?? "",
  databaseUrl: process.env.DATABASE_URL ?? "",
  oAuthServerUrl: process.env.OAUTH_SERVER_URL ?? "",
  ownerOpenId: process.env.OWNER_OPEN_ID ?? "",
  isProduction: process.env.NODE_ENV === "production",
  forgeApiUrl: process.env.BUILT_IN_FORGE_API_URL ?? "",
  forgeApiKey: process.env.BUILT_IN_FORGE_API_KEY ?? "",
  csoSheetId: process.env.CSO_SHEET_ID ?? "",
  csoKivGid: process.env.CSO_KIV_GID ?? "",
  csoSignedGid: process.env.CSO_SIGNED_GID ?? "",
  csoDailyGid: process.env.CSO_DAILY_GID ?? "",
  salesOverviewUrl: process.env.SALES_OVERVIEW_URL ?? "",
  salesOverviewToken: process.env.SALES_OVERVIEW_TOKEN ?? "",
};
